import {
AlertTriangle,
ArrowRight,
Check,
ChevronLeft,
ChevronRight,
ChevronDown,
Command,
CreditCard,
File,
FileText,
HelpCircle,
Image,
ImageOff,
Laptop,
Loader2,
LogOut,
Mail,
Moon,
MoreVertical,
Pizza,
Plus,
RefreshCw,
Settings,
SunMedium,
Trash,
Twitter,
User,
X,
Instagram,
Facebook,
Github,
Chrome,
MessageCircle,
BarChart3,
Users,
Calendar,
DollarSign,
TrendingUp,
TrendingDown,
Download,
Filter,
Clock,
Phone,
Search,
Video,
Eye,
Edit,
Palette,
Bell,
Sun,
Monitor,
Shield,
UserCircle,
Crown,
AlertCircle,
Home,
CheckCircle,
XCircle,
ArrowUpRight,
ArrowDownRight,
Star,
PanelLeft,
Folder,
Share,
MoreHorizontal,
Camera,
type Icon,
} from 'lucide-react';

export type { Icon };

export const Icons = {
  // Basic UI
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  ellipsis: MoreVertical,
  ellipsisH: MoreHorizontal,
  add: Plus,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  help: HelpCircle,
  check: Check,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  
  // Navigation & Actions
  settings: Settings,
  home: Home,
  search: Search,
  filter: Filter,
  refresh: RefreshCw,
  download: Download,
  edit: Edit,
  trash: Trash,
  eye: Eye,
  
  // User & Auth
  user: User,
  userCircle: UserCircle,
  users: Users,
  shield: Shield,
  crown: Crown,
  logout: LogOut,
  
  // Business Icons
  dashboard: BarChart3,
  analytics: BarChart3,
  calendar: Calendar,
  clock: Clock,
  dollarSign: DollarSign,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  star: Star,
  
  // Media & Content
  image: Image,
  imageOff: ImageOff,
  video: Video,
  camera: Camera,
  file: File,
  fileText: FileText,
  folder: Folder,
  share: Share,
  
  // Theme & Appearance
  sun: Sun,
  sunMedium: SunMedium,
  moon: Moon,
  monitor: Monitor,
  laptop: Laptop,
  palette: Palette,
  
  // Communication
  mail: Mail,
  phone: Phone,
  bell: Bell,
  discord: MessageCircle,
  
  // Social & Branding
  google: Chrome,
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  gitHub: Github,
  
  // Layout
  panelLeft: PanelLeft,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  
  // Billing
  billing: CreditCard,
  
  // Demo/Placeholder
  pizza: Pizza,
};
