import {
AlertCircle,
AlertTriangle,
ArrowDownRight,
ArrowRight,
ArrowUpRight,
BarChart3,
Bell,
Calendar,
Camera,
Check,
CheckCircle,
ChevronDown,
ChevronLeft,
ChevronRight,
Chrome,
Clock,
Command,
CreditCard,
Crown,
DollarSign,
Download,
Edit,
Eye,
Facebook,
File,
FileText,
Filter,
Folder,
Github,
HelpCircle,
Home,
type Icon,
Image,
ImageOff,
Instagram,
Laptop,
Loader2,
LogOut,
Mail,
MessageCircle,
Monitor,
Moon,
MoreHorizontal,
MoreVertical,
Palette,
PanelLeft,
Phone,
Pizza,
Plus,
RefreshCw,
Search,
Settings,
Share,
Shield,
Star,
Sun,
SunMedium,
Trash,
TrendingDown,
TrendingUp,
Twitter,
User,
UserCircle,
Users,
Video,
X,
XCircle,
} from 'lucide-react';

export type { Icon };

export const Icons = {
  // Basic UI
  logo: Command,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  ellipsis: MoreVertical,
  ellipsisH: MoreHorizontal,
  add: Plus,
  warning: AlertTriangle,
  arrowRight: ArrowRight,
  help: HelpCircle,
  check: Check,
  checkCircle: CheckCircle,
  xCircle: XCircle,
  alertCircle: AlertCircle,
  
  // Navigation & Actions
  settings: Settings,
  home: Home,
  search: Search,
  filter: Filter,
  refresh: RefreshCw,
  download: Download,
  edit: Edit,
  trash: Trash,
  eye: Eye,
  
  // User & Auth
  user: User,
  userCircle: UserCircle,
  users: Users,
  shield: Shield,
  crown: Crown,
  logout: LogOut,
  
  // Business Icons
  dashboard: BarChart3,
  analytics: BarChart3,
  calendar: Calendar,
  clock: Clock,
  dollarSign: DollarSign,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  star: Star,
  
  // Media & Content
  image: Image,
  imageOff: ImageOff,
  video: Video,
  camera: Camera,
  file: File,
  fileText: FileText,
  folder: Folder,
  share: Share,
  
  // Theme & Appearance
  sun: Sun,
  sunMedium: SunMedium,
  moon: Moon,
  monitor: Monitor,
  laptop: Laptop,
  palette: Palette,
  
  // Communication
  mail: Mail,
  phone: Phone,
  bell: Bell,
  discord: MessageCircle,
  
  // Social & Branding
  google: Chrome,
  facebook: Facebook,
  instagram: Instagram,
  twitter: Twitter,
  gitHub: Github,
  
  // Layout
  panelLeft: PanelLeft,
  arrowUpRight: ArrowUpRight,
  arrowDownRight: ArrowDownRight,
  
  // Billing
  billing: CreditCard,
  
  // Demo/Placeholder
  pizza: Pizza,
};
